# Generated by Django 2.0.2 on 2019-07-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
